//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int ID { get; set; }
        public Nullable<double> Value { get; set; }
        public string Text { get; set; }
        public DateTime? Date { get; set; }
        public string FK_SubCategory { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
